### ISSUE TITLE
Question When VM-Exited

### ISSUE THREAD

**Issue by mutiancheng** [tandasat/DdiMon#11]
When VM-Exit occured and it hasn't vmresumed, if Thread Dispatching is activiated what should happen? 
1. Can threads on none-root CPU be dispatched to the VM-Exited CPU?
2.On VM-Exited CPU, shouldn't the current thread be dispatched to other non-root CPUs?

**Comment by tandasat** [comment]
While VM-exit is being processed, any interruptions should not be allowed, as the processor is on the more privileged code and we do not want it to run arbitrary kernel code. So 2 is correct (actually, should not be dispatched to anyone else)

**Comment by mutiancheng** [comment]
When VM-exit occurs, if IF=1 and IRQL<DISPATCH_LEVEL, how can you ensure that the current CPU will not to be dispatched to run another thread?

**Comment by tandasat** [comment]
A host's (VMM's) flag register is loaded from VMCS and not affected by
guest's status.Also, the IF flag is always cleared for the host if I recall
correctly (I was not able to find the statement in the SDM, so could be
wrong). If interrupts are disabled, a thread is not dispatched as timer
interrupt does not occur.


Best,
Satoshi

**Comment by tandasat** [comment]
Sorry, I gave you an wrong answer. As "Loading Host RIP, RSP, and RFLAGS"
states, `RFLAGS is cleared, except bit 1, which is always set.` So the TF flag is always zero, unless you manually enable it.

**Comment by mutiancheng** [comment]
Yes, I observed it with WinDbg. Thank you for your patience and attentiveness. Are the states in the SDM? I will read it.

**Comment by tandasat** [comment]
No problem :) and yes, that is in the SDM.
