### ISSUE TITLE
vm support detection in runtime

### ISSUE THREAD

**Issue by chico-depressive** [tandasat/DdiMon#12]
hello sir satothi!

I am trying to figure out a way to detect (both AMD and INTEL) if VTx are enabled, can you help me with this?

**Comment by tandasat** [comment]
Hey,

I assume you are asking ways to detect if OS is on a VM. Then it is often indicated by the bit 31 of ECX returned by CPUID leaf 0x1. Search "hypervisor" here:
https://en.wikipedia.org/wiki/CPUID#EAX.3D1:_Processor_Info_and_Feature_Bits
It is, however, up to underneath hypervisors whether this bit is set, and some will not. In this case, you may need to look for other implementation specific footprints.

If you can elaborate what you are trying to do, I can probably give more specific answers.

**Comment by chico-depressive** [comment]
@tandasat sotty for not explaining it well, here is asked more detailed: https://github.com/cheat-engine/cheat-engine/issues/169

reading msr is the only way to tell if VMX is enabled and supported by processor?

**Comment by tandasat** [comment]
Hey, to tell if VT-x is supported by the processor, you could check CPUID (leaf 1) and check ECX as explained in "DISCOVERING SUPPORT FOR VMX" in the Intel SDM. Then, you could check whether the VT-x is enabled by BIOS by reading the MSR as explained in "ENABLING AND ENTERING VMX OPERATION." 


For AMD processors, you could check bit 2 of ECX returned by CPUID leaf 0x80000001, and then query IA32_MSR_EFER (0xc0000080) and see if bit 12 is set. More comprehensive logic is shown in "Enabling SVM" in the AMD64 Architecture Programmer’s Manual Volume 2.

**Comment by chico-depressive** [comment]
@tandasat thank you, reading MSR registers can be done only in kernelmode right?

**Comment by tandasat** [comment]
Yes, that is correct.
