### ISSUE TITLE
ShEnableHooks and ShDisableHooks in shadow_hook.cpp

### ISSUE THREAD

**Issue by zl950402** [tandasat/DdiMon#14]
why 
HypercallNumber::kShEnablePageShadowing and 
HypercallNumber::kShDisablePageShadowing 
are missing?

**Comment by tandasat** [comment]
Hey, did you pull down files recursively?
`$git clone --recursive https://github.com/tandasat/DdiMon.git`

**Comment by zl950402** [comment]
Yes.
And HypercallNumber in [HyperPlatform/util.h](https://github.com/tandasat/HyperPlatform/blob/master/HyperPlatform/util.h) there is no kShEnablePageShadowing and kShDisablePageShadowing

**Comment by tandasat** [comment]
That is weird. Can you manually checkout 374db11ecefd1f00acccbc34fec6c1013e6f080c in DdiMon/HyperPlatform? That commit is what the DdiMon expects.
