### ISSUE TITLE
Little issue hooking NtUserBuildHwndList and other Win32kfull routines

### ISSUE THREAD

**Issue by koemeet** [tandasat/DdiMon#15]
I am trying to hook some routines in `win32kfull.sys`, such as `NtUserBuildHwndList` and I was able to let it place the shadow hook without any errors:

![](https://i.gyazo.com/807f2058cae2afe1fa18d36e311596fe.png)

Although there are no errors reported and it is properly patching the proper exported routine, the hook doesn't seem to work and I am not able to intercept any calls made to `win32full.sys`. I am aware that it isn't mapped in system space, but in session space, so I am attaching to a random process first.

I am setting it up like this:

```cpp
// attach to own user-mode test program so we are able to access the session space.
KeAttachProcess(process);
status = DdimonpEnumExportedSymbols(reinterpret_cast<ULONG_PTR>(win32kBase),
    DdimonpEnumExportedSymbolsCallback,
    shared_sh_data);
KeDetachProcess();
```

Also, hooking anything from `ntoskrnl` goes without any issues.

Any ideas on why the hook isn't picking up? Am I approaching this maybe in the wrong way? Thanks in advance for any effort into helping me out.

**Comment by koemeet** [comment]
I was able to successfully hook it by setting `Cr3` to the user-mode process Cr3's value when getting the physical address from the virtual address (`UtilPaFromVa`). Hooking win32k routines is now working properly 😄!

Apart from `NtUserBuildHwndList` all hooks seem to work properly. Hooking `NtUserBuildHwndList` will cause a crash of explorer itself when `explorer.exe` restarts or when you open a new window in it.

**Comment by tandasat** [comment]
Awesome! Glad you figured out the cause so quickly.

**Comment by zl950402** [comment]
@koemeet how do you do that finally?

**Comment by RangeMachine** [comment]
Sorry for bumping old issue, but heres info how to make it if some one needed in future:
1. Modify HookInformation struct by adding **ULONG_PTR  target_cr3;** 
![image](https://user-images.githubusercontent.com/11577601/43805674-5cdb107a-9aa9-11e8-8ca4-0b33d4668fbc.png)

2. Modify ShpCreateHookInformation by adding **info->target_cr3 = __readcr3();**
![image](https://user-images.githubusercontent.com/11577601/43805723-8b8d794e-9aa9-11e8-9694-9099530c7c94.png)

3. Modify ShpEnablePageShadowingForExec, ShpEnablePageShadowingForRW, ShpDisablePageShadowing by adding  **const auto cr3 = __readcr3();  __writecr3(info.target_cr3);** into the top of each and **__writecr3(cr3);** into the bottom of each
![image](https://user-images.githubusercontent.com/11577601/43805829-f2688b9a-9aa9-11e8-80da-bbf4b365cc77.png)

4. Hook example
`
KeAttachProcess(pe_csrss);
ShInstallHook(g_pSharedShData, fNtUserBuildHwndList, &g_hookTargets[3]);
KeDetachProcess();
ShEnableHooks();
`

This can be used to hook any usermode program.

**Comment by tandasat** [comment]
@RangeMachine Thanks for sharing the trick! This should be useful for those who face the same challenge find this thread.
