### ISSUE TITLE
problem when compiling

### ISSUE THREAD

**Issue by rout3rx** [tandasat/DdiMon#18]
Hello
i have a problem with compiling
on x86 : 
a hypervisior feature is not available to the user
on x64:
this driver has been blocked from loading.
why?
could anyone help?

**Comment by tandasat** [comment]
Hi, 

For the issue with x86, please double check if VT-x is available on the system. This message can be seen when a processor (or BIOS) does support VT-x. You might find more information in HyperPlatform.log.

 On x64, did you enable the test signing mode? Please make sure the system is under the test signing  mode and try it again.

**Comment by rout3rx** [comment]
thanks,
dear tandasat
this means i can't compile it on a VM on esxi. correct?

**Comment by tandasat** [comment]
You can compile it, and can install it if the VM is configured to support nested virtualization. I am not terribly familiar with ESXi but believe you can enable nested virtualization. Please search manual etc for the instructions.

**Comment by rout3rx** [comment]
yes i enabled.
![photo_2017-09-26_21-14-01](https://user-images.githubusercontent.com/30006945/30875211-a2f545a0-a2ff-11e7-83e4-44b10559e5ab.jpg)

**Comment by tandasat** [comment]
do you see any logs in HyperPlatform.log?

**Comment by rout3rx** [comment]
could you say, where is this file located?

**Comment by tandasat** [comment]
It's under \Windows.

**Comment by rout3rx** [comment]
no,nothing find.

**Comment by tandasat** [comment]
No, should not be. I cannot think of a reason of the error. Maybe you can recompiling the driver, make sure you copied the x64 version of the SYS file, and/or do the same flow for other x64 VM.

Sorry, I cannot be much help.

**Comment by rout3rx** [comment]
i think this package have some problem. 
i test it on a real machine (not VM) with windows 8.1 but have this error :

C:\Windows\system32>sc start ddimon
[SC] StartService FAILED 1275:

This driver has been blocked from loading


C:\Windows\system32>

**Comment by rout3rx** [comment]
![photo_2017-09-27_22-11-37](https://user-images.githubusercontent.com/30006945/30931269-0a3f727c-a3d1-11e7-9f67-d485314acbe5.jpg)
i have this problem in compilation.
i use and add kit10 but after add and at the end of compile crashed.

**Comment by rout3rx** [comment]
![photo_2017-09-29_10-41-03](https://user-images.githubusercontent.com/30006945/31004777-bc41aeb8-a502-11e7-93e8-7afdd06c78b8.jpg)

a new problem occures after compile.

**Comment by tandasat** [comment]
Did this still occur with the latest code? Also, try again using the latest SDK and WDK.

**Comment by tandasat** [comment]
Closing this as it does not repro. Feel free to reopen the issue with detailed steps to reproduce the issue. Thank you.
