### ISSUE TITLE
Hiding memory pages of user-mode DLL 

### ISSUE THREAD

**Issue by mrtiggles5** [tandasat/DdiMon#19]
Hi Tandasat,
I have basically modified DdiMon to suit my needs in order to hide the memory pages of a user-mode DLL injected into an arbitrary process - it works much like Ddimon with a few caveats. 
- it works in user-mode and makes note of the user-mode pages allocated for the DLL
- sets read/write access of the corresponding EPT pages to be false while setting execution access to be true
- Upon EPT violation, the handler sets the EPT page to redirect to a null page before setting the MTF and resetting the last modified memory page in the MTF handler to point to the original page. 

The purpose of this is to prevent people from dumping the contents of the DLL from memory back onto disk and from preventing signature scans for my DLL. While my code works in hiding the DLL, the target process crashes. 

Do you happen to know why this happens? I had a suspicion that this might have been triggered by code in the .text section accessing elements in the .data section so I then only applied protection to the .text section, but the same thing happens - the process still crashes. When I apply this protection to a DLL that merely executes junk in a while(true) loop everything is able to work fine. I also make sure to use VirtualLock() in order to prevent the user-mode memory from being paged out.

**Comment by tandasat** [comment]
Hi @mrtiggles5,

My guess is that protected code (your DLL code) attempted to read from the protected region and got 0 while it should have gotten something. You might already added logic to handle such cases, but it not the case, it is probably worth tracing EPT violation and exception information to see if that is happening.

**Comment by mrtiggles5** [comment]
@tandasat thanks for the reply,
so I just want to clear a quick question up - would protecting the .data section of my DLL cause an EPT violation when code in the DLL's .text section references the global variables or strings allocated in the .data section?

**Comment by tandasat** [comment]
Yes, it will trigger EPT violation when the data section is non-readable/non-writable even if a processor is executing the .text section (which is readable/writable/executable)

**Comment by stonedreamforest** [comment]
@mrtiggles5  Hello, Can you share how to solve this problem? thanks.
