### ISSUE TITLE
Wake up the computer blue screen and solution

### ISSUE THREAD

**Issue by isdebug** [tandasat/DdiMon#21]
Hello, ddimon project wake up the computer BSOD, the reason is.
-#pragma alloc_text(INIT, DdimonInitialization)
+#pragma alloc_text(PAGE, DdimonInitialization)

and

#pragma alloc_text(INIT, ShAllocateShadowHookData)
#pragma alloc_text(INIT, ShAllocateSharedShaowHookData)
#pragma alloc_text(INIT, ShEnableHooks)
#pragma alloc_text(INIT, ShInstallHook)
#pragma alloc_text(INIT, ShpSetupInlineHook)
#pragma alloc_text(INIT, ShpGetInstructionSize)
#pragma alloc_text(INIT, ShpMakeTrampolineCode)

All INIT need to be changed PAGE

**Comment by tandasat** [comment]
Confirmed the fix worked. Thanks a lot for providing the solution, @isdebug.
