### ISSUE TITLE
User land API Hooking

### ISSUE THREAD

**Issue by trapframe** [tandasat/DdiMon#23]
Hi Satoshi,

Is  it possible to hook some user land APIs using DdiMon ?
I understand that Ddimon only take cares of the kernel address space, is it possible to specify a user mode process  (through CR3  maybe?)

Thanks

**Comment by tandasat** [comment]
No, DdiMon is not designed for user-mode addresses. 

You could code and extend what DdiMon does for user-mode though. I also did some research on it. I did not make it stable enough but dumped source code of it. You *might* find it interesting. 
https://github.com/tandasat/FU_Hypervisor

**Comment by trapframe** [comment]
Thanks Satoshi, will look into it
