### ISSUE TITLE
Dose DdiMon support windows 10 17134 x86?

### ISSUE THREAD

**Issue by armorunicorn** [tandasat/DdiMon#24]
I tried to run DdiMon on windows 10 17134 x86, but always get BSOD. Is this a version error?
the stack is 
 # ChildEBP RetAddr  Args to Child              
00 818e0f24 8184e779 00000003 bf3ba2f8 00000065 nt!RtlpBreakWithStatusInstruction
01 818e0f78 8184e167 8708c340 818e1394 00000000 nt!KiBugCheckDebugBreak+0x1f
02 818e1368 817c1e02 0000007f 00000008 80a1cc00 nt!KeBugCheck2+0x79d
03 818e138c 817d82a1 0000007f 00000008 80a1cc00 nt!KiBugCheck2+0xc6
04 818e138c b6d42394 0000007f 00000008 80a1cc00 nt!KiTrap08+0x6e
05 af62beb0 b6d43009 3df54360 00000002 b6d421d0 DdiMon!UtilLoadPdptes+0x1e [d:\project\ddimon\hyperplatform\hyperplatform\util.cpp @ 835] 
06 af62bf00 b6d43ec6 af62bf50 00000002 8947d000 DdiMon!VmmpHandleCrAccess+0x1db [d:\project\ddimon\hyperplatform\hyperplatform\vmm.cpp @ 1114] 
07 af62bf40 b6d427e0 af62bf50 00000000 af62bfd8 DdiMon!VmmpHandleVmExit+0x12a [d:\project\ddimon\hyperplatform\hyperplatform\vmm.cpp @ 269] 
08 af62bf64 b6d4106e af62bfd8 00000000 00000000 DdiMon!VmmVmExitHandler+0x5e [d:\project\ddimon\hyperplatform\hyperplatform\vmm.cpp @ 206] 
09 af62bf6c 00000000 00000000 00000000 00000000 DdiMon!AsmVmmEntryPoint+0x37 [D:\project\DdiMon\HyperPlatform\HyperPlatform\Arch\x86\x86.asm @ 117]

**Comment by tandasat** [comment]
It should have been but has been broken for a while. This is the same issue as the one reported here.
https://github.com/tandasat/HyperPlatform/issues/54

I was de-prioritizing this issue over the other things as I thought almost nobody cared x86 anymore, but good to know it was potentially still a thing. I will try to find time within a couple of months for this.

**Comment by tandasat** [comment]
Yes, it should be fine on the latest x64 Windows 10.

**Comment by armorunicorn** [comment]
thank you very much~

**Comment by tandasat** [comment]
@armorunicorn I have updated the DdiMon (and HyperPlatform) with the updates which I believe to fix the issue. If you can pull the changes and confirm if it works fine, that would be great, since I only have Windows 7 for x86 handy.
