### ISSUE TITLE
Countering HV detections

### ISSUE THREAD

**Issue by frostiest** [tandasat/DdiMon#36]
@tandasat this article https://secret.club/2020/04/13/how-anti-cheats-detect-system-emulation.html has a lot of detection vectors. I've managed to counter a good majority of them ( I think) thanks to his information, but i'm not sure how to handle the INVD/WBINVD one and was hoping you'd give some tips. 

for the XSETBV one, here's definitions he uses that I managed to find different places online (took awhile)

`#define X86_XCR0_FP_POS 0
#define X86_XCR0_FP (1ULL << X86_XCR0_FP_POS)
#define X86_XCR0_SSE_POS 1
#define X86_XCR0_SSE (1ULL << X86_XCR0_SSE_POS)
#define X86_XCR0_YMM_POS 2
#define X86_XCR0_YMM (1ULL << X86_XCR0_YMM_POS)
#define X86_XCR0_BNDREGS_POS 3
#define X86_XCR0_BNDREGS (1ULL << X86_XCR0_BNDREGS_POS)
#define X86_XCR0_BNDCSR_POS 4
#define X86_XCR0_BNDCSR (1ULL << X86_XCR0_BNDCSR_POS)
#define X86_XCR0_OPMASK_POS 5
#define X86_XCR0_OPMASK (1ULL << X86_XCR0_OPMASK_POS)
#define X86_XCR0_ZMM_POS 6
#define X86_XCR0_ZMM (1ULL << X86_XCR0_ZMM_POS)
#define X86_XCR0_HI_ZMM_POS 7
#define X86_XCR0_HI_ZMM (1ULL << X86_XCR0_HI_ZMM_POS)
#define X86_XCR0_PKRU_POS 9
#define X86_XCR0_PKRU (1ULL << X86_XCR0_PKRU_POS)
#define X86_XCR0_LWP_POS 62
#define X86_XCR0_LWP (1ULL << X86_XCR0_LWP_POS)

#define X86_XSTATE_X87 (1ULL << 0)
#define X86_XSTATE_SSE (1ULL << 1)
#define X86_XSTATE_AVX (1ULL << 2)
#define X86_XSTATE_BNDREGS (1ULL << 3)
#define X86_XSTATE_BNDCFG (1ULL << 4)
#define X86_XSTATE_MPX (X86_XSTATE_BNDREGS | X86_XSTATE_BNDCFG)

/* AVX 512 adds three feature bits.  All three must be enabled.  */
#define X86_XSTATE_K (1ULL << 5)
#define X86_XSTATE_ZMM_H (1ULL << 6)
#define X86_XSTATE_ZMM (1ULL << 7)
#define X86_XSTATE_AVX512 (X86_XSTATE_K | X86_XSTATE_ZMM_H | X86_XSTATE_ZMM)

#define X86_XSTATE_PKRU (1ULL << 9)

/* Supported mask and size of the extended state.  */
#define X86_XSTATE_X87_MASK X86_XSTATE_X87
#define X86_XSTATE_SSE_MASK (X86_XSTATE_X87 | X86_XSTATE_SSE)
#define X86_XSTATE_AVX_MASK (X86_XSTATE_SSE_MASK | X86_XSTATE_AVX)
#define X86_XSTATE_MPX_MASK (X86_XSTATE_SSE_MASK | X86_XSTATE_MPX)
#define X86_XSTATE_AVX_MPX_MASK (X86_XSTATE_AVX_MASK | X86_XSTATE_MPX)
#define X86_XSTATE_AVX_AVX512_MASK (X86_XSTATE_AVX_MASK | X86_XSTATE_AVX512)
#define X86_XSTATE_AVX_MPX_AVX512_PKU_MASK \
  (X86_XSTATE_AVX_MPX_MASK | X86_XSTATE_AVX512 | X86_XSTATE_PKRU)

#define X86_XSTATE_ALL_MASK (X86_XSTATE_AVX_MPX_AVX512_PKU_MASK)

#define X86_XSTATE_SSE_SIZE 576
#define X86_XSTATE_AVX_SIZE 832
#define X86_XSTATE_BNDREGS_SIZE 1024
#define X86_XSTATE_BNDCFG_SIZE 1088
#define X86_XSTATE_AVX512_SIZE 2688
#define X86_XSTATE_PKRU_SIZE 2696
#define X86_XSTATE_MAX_SIZE 2696

#define XCR_XFEATURE_ENABLED_MASK 0x00000000`

**Comment by tandasat** [comment]
This project can still detected by the INVD approach, yes?  Looking at code, it calls `invd` to emulate the instruction and not write-back one, so I would (naively) think that detection does not apply to this.

If that's the case, I am not sure what you can do. Studying when cache might be written-back to system memory and trying to avoid that from occurring would be what I would do.

**Comment by frostiest** [comment]
thanks, i'll test it out and see if it detects hyperplatform in general, I automatically assumed it does but perhaps it doesn't.

**Comment by frostiest** [comment]
yeah unfortunately it detects inside vmware(no surprise), then on the main system it just freezes after hyperplatform is loaded. Not handling invd in hyperplatform is instant crash so obviously i'll need to figure out a way to handle this

`TestInvd PROC
pushfq
cli
push 1                 ; Set cache data
wbinvd                 ; Flush writeback data set from previous instruction to system memory.
mov byte ptr [rsp], 0  ; Set memory to 0. This is in WB memory so it will not be in system memory.
invd                   ; Flush the caches but do not write back to system memory. Real hardware will result in loss of previous operation.
pop rax                ; Proper system behaviour will have AL = 1; Hypervisor/emulator that uses WBINVD or does nothing will have AL = 0.
popfq
ret
TestInvd ENDP`

i'll test things and see if I can find a solution, and will share if I do

**Comment by frostiest** [comment]
I still haven't quiet resolved it but what i'm testing is
1) intercepting Wbinvd
2) saving partial stack data for the last call to Wbinvd
3) then setting saved partial stack data when invd is called

I first replaced invd with wbinvd because the hvpp author is likely correct in invd being dangerous

`
; void __stdcall AsmInvalidateInternalCaches();
AsmInvalidateInternalCaches PROC
    ;invd
    wbinvd
    ret
AsmInvalidateInternalCaches ENDP

`
then I enabled  Wbinvd intercepting

`
  vm_procctl2_requested.fields.wbinvd_exiting = true;
`
`
  case VmxExitReason::kWbinvd:
      VmmpHandleWbinvd(guest_context);
      break;
`

then i'm trying to save relevant stack data 

`
GuestContext TmpContext = {0};
int ignorenext = 0;

_Use_decl_annotations_ static void VmmpHandleWbinvd( GuestContext *guest_context) {

  if (ignorenext == 0) {
    memcpy(&TmpContext, guest_context, sizeof(GuestContext));
  }

  AsmInvalidateInternalCaches();
  VmmpAdjustGuestInstructionPointer(guest_context);
}

`

where i'm struggling is setting the stack data inside invd function. I tried many things including
manually setting for testing
`
   int set1 = 1;
    memcpy(&guest_context->stack->gp_regs.sp, &set1, sizeof(int));
    UtilVmWrite(VmcsField::kGuestRsp, guest_context->stack->gp_regs.sp);
`
but not quite there yet, still returning 0
