### ISSUE TITLE
vs2019 compilation error

### ISSUE THREAD

**Issue by taodaqiao** [tandasat/DdiMon#39]
2>shadow_hook.obj : error LNK2019: Unresolved external symbol _invoke_watson，Function "protected: virtual void __cdecl stdext::bad_alloc::_Doraise(void)const " (?_Doraise@bad_alloc@stdext@@MEBAXXZ) 

2>shadow_hook.obj : error LNK2001: Unresolved external symbol "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA)

**Comment by botao1995** [comment]
这有人提过这个问题，请看：
https://github.com/tandasat/DdiMon/issues/34

**Comment by tandasat** [comment]
Closing as duplication #34
