### ISSUE TITLE
Missing method due to new version of hyperplatform

### ISSUE THREAD

**Issue by SiyerBOBO** [tandasat/DdiMon#42]
Hello, author, there are methods missing in the **shadow_hook.cpp** file of your project, including: **KShEnablePageShadowing**{Line 209} and **kShDisablePageShadowing**{Line 221}, which were reported in **[#14](https://github.com/tandasat/DdiMon/issues/14)**, are currently identified as missing methods from **HyperPlatform/util.h**, It is presumed that the HyperPlatform version is updated. Here are the details:
![image](https://user-images.githubusercontent.com/47243555/150631999-cb5c27d8-cada-4660-af3a-a82db4d0f453.png)
About the code definition here (in HyperPlatform/utils.h):
![image](https://user-images.githubusercontent.com/47243555/150632023-4d099975-3e2b-478e-a065-4c0d4e1c078d.png)

Thank you for your dedication to Intel VT EPT hook technology. This project provides me with very valuable technical support for understanding and using this technology. I look forward to and pay attention to the repair progress of this problem, and I will complete my master's graduation project on this basis. I look forward to your repair or alternative opinions.

**Comment by tandasat** [comment]
I was able to build the project. Make sure to pull the repo recursively. 
```
$git clone --recursive https://github.com/tandasat/DdiMon.git
```

I pushed unrelated build failures related to INF etc. Nuke and pull the repo again.

**Comment by SiyerBOBO** [comment]
Oddly enough, the above problem did occur in the project I downloaded and compiled separately, but as you mentioned, the problem disappeared with git recursive cloning. The required fields exist after observing the HyperPlatform. Thank you for your advice in your busy life.
![image](https://user-images.githubusercontent.com/47243555/150663218-c65260d0-92dc-4622-b8c9-e102bc7cbc1c.png)
