### ISSUE TITLE
Hello, I noticed your project FU_ Hypervisor, do you plan to continue maintenance?

### ISSUE THREAD

**Issue by 07bug** [tandasat/DdiMon#45]
I am very interested in cheating and anti cheating technology, and I noticed that FU_ Hypervisor, but this project is no longer maintained, but I am very interested in this project. Do you plan to continue maintenance

**Comment by tandasat** [comment]
Hey. No I don’t know plan to maintain FU project. I am even intending not to actively take time to support DdiMon.

**Comment by jimster480** [comment]
How come you are abandoning ddimon?

**Comment by tandasat** [comment]
All about priorities.
