### ISSUE TITLE
How cound i use ShpEnablePageShadowingForRW hide kernel memory?

### ISSUE THREAD

**Issue by LYingSiMon** [tandasat/DdiMon#46]
Hello, the question has bothered me for a long time, I tried to use ShpEnablePageShadowingForRW ShEnablePageShadowing function to hide the nt! The memory of NtCreateFile looks like this:

```
_Use_decl_annotations_ NTSTATUS ShEnablePageShadowing(
    EptData* ept_data, const SharedShadowHookData* shared_sh_data) {
  //HYPERPLATFORM_COMMON_DBG_BREAK();

  // ======== mycode
  __debugbreak();
  HookInformation HookInfo = {0};
  PVOID64 vAddr = ExAllocatePoolWithTag(NonPagedPool, 0x1000, 'lysd');
  RtlZeroMemory(vAddr, 0x1000);

  HookInfo.patch_address = (void*)0xfffff8021caefa50;  // nt!NtCreateFile:
  HookInfo.pa_base_for_rw = UtilPaFromVa(vAddr);

  ShpEnablePageShadowingForRW(HookInfo, ept_data);
  // ======== mycode

  for (auto& info : shared_sh_data->hooks) {
    ShpEnablePageShadowingForExec(*info, ept_data);
  }

  return STATUS_SUCCESS;
}
```

The good news is that it works, the bad news is that it bluescreens 😅
![image](https://user-images.githubusercontent.com/51651107/204471748-9cc54c8d-d7bd-4486-85d1-d6d729921744.png)

the dump file(os version is win10 1909 x64)
[112922-9890-01.zip](https://github.com/tandasat/DdiMon/files/10110932/112922-9890-01.zip)

Please give me some advice,thank you 🙂

**Comment by tandasat** [comment]
It seems as though hiding is not working proper to me. Crash dump should not be able to view actual contents at NtCreateFile, like your screenshot. 
![image](https://user-images.githubusercontent.com/1620923/204842409-e6a49508-aab0-4e87-a446-c9776e0b9888.png)
 
Did you try adding NtCreateFile-entry into `g_ddimonp_hook_targets`? Code is structured to depend on that list for adding new hooks

**Comment by LYingSiMon** [comment]
> 似乎隐藏对我来说不合适。崩溃转储不应该能够在 NtCreateFile 中查看实际内容，就像您的屏幕截图一样。 ![图片](https://user-images.githubusercontent.com/1620923/204842409-e6a49508-aab0-4e87-a446-c9776e0b9888.png)
> 
> 您是否尝试将 NtCreateFile-entry 添加到其中`g_ddimonp_hook_targets`？代码的结构取决于该列表以添加新的挂钩

The NtCreateFile in your screenshot is not hidden, why is that? Do you mean that the hiding failed, or is windbg's display problem? 😮

**Comment by LYingSiMon** [comment]
> It seems as though hiding is not working proper to me. Crash dump should not be able to view actual contents at NtCreateFile, like your screenshot. ![image](https://user-images.githubusercontent.com/1620923/204842409-e6a49508-aab0-4e87-a446-c9776e0b9888.png)
> 
> Did you try adding NtCreateFile-entry into `g_ddimonp_hook_targets`? Code is structured to depend on that list for adding new hooks

Thank you for your reply.

Sorry my bad English . The NtCreateFile in your screenshot is not hidden. Why is that? Do you mean that the hiding failed, or is windbg's display problem?

I think it should be a display error, because when I blue screen, NtCreateFile NtWriteFile's memory is hidden (their address is closer), while NtWriteFile's memory is normal
![image](https://user-images.githubusercontent.com/51651107/205024877-c59c4009-2307-4822-92db-e5604378785b.png)

**Comment by LYingSiMon** [comment]
I don't add anything in g_ddimonp_hook_targets because my final goal is not to Hook the NtCreateFile , but to hide the memory of NtCreateFile . I don't know how to write the handler function, which makes me confused 🤔

Or, maybe I should write handler as null?
![image](https://user-images.githubusercontent.com/51651107/205026820-7ee65ef2-511f-43d0-9c04-660049d4b27a.png)
like this?
![image](https://user-images.githubusercontent.com/51651107/205027156-f6a6f6c5-d7f1-4b3a-9dea-16efb9a333a8.png)

**Comment by tandasat** [comment]
Fair enough. I am not sure if that's easy to achieve with modification of DdiMon, as it is written for hooking. You might have to hack around and fight against with existing code. I suggest you to spend more time to study code and potentially rewrite it for yourself.

**Comment by LYingSiMon** [comment]
I see. Thank you. It seems that I need more study
