### ISSUE TITLE
Monitoring any execution inside .text section

### ISSUE THREAD

**Issue by chico-depressive** [tandasat/DdiMon#9]
hey @tandasat amazing job dude, I love your codes!

I am trying to know if ddimon can be used to detect execution inside some memory range, or can be used only as inline hooking? 

It puts the whole OS in supervised mode? Is possible to run it inside virtualbox?

**Comment by tandasat** [comment]
Hey,

This is designed for inline hooking, and detection of execution is not bread and butter of this project. 
MemoryMon (https://github.com/tandasat/MemoryMon/) is written exactly for that purpose, however. I may want to check it out.

Yes all my hypervisors visualize whole OS, and cannot run inside VirtualBox.

**Comment by chico-depressive** [comment]
@tandasat thank you sir, for your help! I am going to read the source code of MemoryMon
